# Anthony Wolfe Notebook for Census Bureau Exploration

#### Note: Worked with Jonathan and others but notebooks kept separate for productivity

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

In [3]:
all_df = pd.read_csv('../data/all-ages.csv')

In [4]:
all_df.head().sort_values("Major_code")

,index,Major_code,Major,Major_category,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th
0,0,1100,GENERAL AGRICULTURE,Agriculture & Natural Resources,128148,90245,74078,2423,0.026147,50000,34000,80000.0
1,1,1101,AGRICULTURE PRODUCTION AND MANAGEMENT,Agriculture & Natural Resources,95326,76865,64240,2266,0.028636,54000,36000,80000.0
2,2,1102,AGRICULTURAL ECONOMICS,Agriculture & Natural Resources,33955,26321,22810,821,0.030248,63000,40000,98000.0
3,3,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,103549,81177,64937,3619,0.042679,46000,30000,72000.0
4,4,1104,FOOD SCIENCE,Agriculture & Natural Resources,24280,17281,12722,894,0.049188,62000,38500,90000.0

In [5]:
all_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   index                          173 non-null    int64
 1   Major_code                     173 non-null    int64
 2   Major                          173 non-null    str
 3   Major_category                 173 non-null    str
 4   Total                          173 non-null    int64
 5   Employed                       173 non-null    int64
 6   Employed_full_time_year_round  173 non-null    int64
 7   Unemployed                     173 non-null    int64
 8   Unemployment_rate              173 non-null    float64
 9   Median                         173 non-null    int64
 10  P25th                          173 non-null    int64
 11  P75th                          173 non-null    float64
dtypes: float64(2), int64(8), str(2)
memory usage: 16.3 KB

In [6]:
all_df.describe().T

,count,mean,std,min,25%,50%,75%,max
index,173.0,86.000000,50.084928,0.0,43.000000,86.000000,129.000000,1.720000e+02
Major_code,173.0,3879.815029,1687.753140,1100.0,2403.000000,3608.000000,5503.000000,6.403000e+03
Total,173.0,230256.635838,422068.483149,2396.0,24280.000000,75791.000000,205763.000000,3.123510e+06
Employed,173.0,166161.982659,307324.399668,1492.0,17281.000000,56564.000000,142879.000000,2.354398e+06
Employed_full_time_year_round,173.0,126307.774566,242425.389073,1093.0,12722.000000,39613.000000,111025.000000,1.939384e+06
Unemployed,173.0,9725.034682,18022.040192,0.0,1101.000000,3619.000000,8862.000000,1.472610e+05
Unemployment_rate,173.0,0.057355,0.019177,0.0,0.046261,0.054719,0.069043,1.561475e-01
Median,173.0,56816.184971,14706.226865,35000.0,46000.000000,53000.000000,65000.000000,1.250000e+05
P25th,173.0,38697.109827,9414.524761,24900.0,32000.000000,36000.000000,42000.000000,7.800000e+04
P75th,173.0,82506.358382,20805.330126,45800.0,70000.000000,80000.000000,95000.000000,2.100000e+05

In [7]:
# Major category specific numeric-only table for grouping logic

num_cols_list = all_df.select_dtypes(include="number").columns.to_list()
#num_cols_list.append("Major")
num_cols_list.append("Major_category")
num_cols_list.remove("index")
num_cols_list.append("Major_code")
all_df_num = all_df[num_cols_list]
#all_df_num.groupby(by="Major").mean().sort_values("Major_code")
all_df_num.head()

,Major_code,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,Major_category,Major_code
0,1100,128148,90245,74078,2423,0.026147,50000,34000,80000.0,Agriculture & Natural Resources,1100
1,1101,95326,76865,64240,2266,0.028636,54000,36000,80000.0,Agriculture & Natural Resources,1101
2,1102,33955,26321,22810,821,0.030248,63000,40000,98000.0,Agriculture & Natural Resources,1102
3,1103,103549,81177,64937,3619,0.042679,46000,30000,72000.0,Agriculture & Natural Resources,1103
4,1104,24280,17281,12722,894,0.049188,62000,38500,90000.0,Agriculture & Natural Resources,1104

In [8]:
all_df_num.groupby("Major_category").mean().round(0)

,Major_code,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,Major_code
Major_category,,,,,,,,,,
Agriculture & Natural Resources,1152.0,63244.0,48042.0,38919.0,1855.0,0.0,55000.0,36550.0,81300.0,1152.0
Arts,6015.0,225733.0,163587.0,106826.0,13016.0,0.0,43525.0,29112.0,64500.0,6015.0
Biology & Life Science,3476.0,95585.0,67647.0,48752.0,4095.0,0.0,50821.0,33214.0,78771.0,3476.0
Business,6213.0,758365.0,579219.0,474717.0,33415.0,0.0,60615.0,41854.0,91462.0,6213.0
Communications & Journalism,1902.0,450956.0,355760.0,267047.0,25300.0,0.0,49500.0,34000.0,76250.0,1902.0
Computers & Mathematics,2703.0,161943.0,128237.0,106380.0,7270.0,0.0,66273.0,43427.0,95818.0,2703.0
Education,2388.0,293757.0,177075.0,116694.0,7834.0,0.0,43831.0,33222.0,58456.0,2388.0
Engineering,2490.0,123311.0,90413.0,76414.0,5048.0,0.0,77759.0,52459.0,108534.0,2490.0
Health,5938.0,245905.0,182724.0,127926.0,6251.0,0.0,56458.0,40067.0,77500.0,5938.0
Humanities & Liberal Arts,4049.0,249222.0,166612.0,116234.0,11942.0,0.0,46080.0,31413.0,70933.0,4049.0
Industrial Arts & Consumer Services,4315.0,147685.0,107683.0,77969.0,5766.0,0.0,52643.0,35064.0,76857.0,4315.0
Interdisciplinary,4000.0,45199.0,35706.0,26038.0,2990.0,0.0,43000.0,32000.0,55000.0,4000.0
Law & Public Policy,4501.0,180585.0,143785.0,120091.0,8610.0,0.0,52800.0,36200.0,78800.0,4501.0
Physical Sciences,5023.0,102532.0,70713.0,54759.0,3822.0,0.0,62400.0,39670.0,92000.0,5023.0
Psychology & Social Work,5258.0,220809.0,156887.0,110365.0,11578.0,0.0,44556.0,31011.0,64333.0,5258.0
Social Science,5348.0,294903.0,207978.0,160038.0,14683.0,0.0,53222.0,37144.0,81222.0,5348.0

In [9]:
major_cat_groups = all_df_num.groupby("Major_category").mean().round(0)

In [ ]:
major_cat_groups.convert_dtypes()